database:
  # host: "localhost"
  host: "postgresql"
  port: "5432"
  user: "postgres"
  pass: "secret"
  dbname: "orders_l0"
  driverName: "pgx"

stan-listener:
  # host: "localhost"
  host: "stan"
  port: "4222"
  cluster_name: "cluster-L0"
  client_id: "orderServer"
  durable_name: "orderSeverSub"
  subject: "orders"

http-server:
  port: "8080"
