version: "3.5"

services:
  nginx:
    container_name: nginx-rev-proxy
    image: nginx:1.23
    ports:
    - "8080:80"
    restart: unless-stopped
    environment:
    - NGINX_HOST=foobar.com
    - NGINX_PORT=80
    networks:
      - mynet
      - mynet-rev-proxy
    volumes:
    - ./volumes/nginx:/etc/nginx/conf.d  

  my-app:
    container_name: my-app
    build: ./
    ports:
      - 8081:8081
    restart: unless-stopped
    depends_on:
      - db
      - stan
    networks:
      - mynet
      - mynet-rev-proxy

  db:
    container_name: db
    image: postgres:12-alpine
    ports:
      - "5432:5432"
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: orders_l0
    networks:
      - mynet
    volumes:
      - ./volumes/db/data:/var/lib/postgresql/data
      # - db:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    networks:
      - mynet

  stan:
    container_name: stan
    image: nats-streaming:0.25.3
    ports:
      - "4222:4222"
      - "8222:8222"
    restart: unless-stopped
    networks:
      - mynet
    command:
      - "-cid=cluster-L0" 
      - "--debug=true"
      # - "--store=file"
      # - "--dir=data" #datastore

networks:
  mynet:
    driver: bridge
  mynet-rev-proxy:
    driver: bridge

# volumes:
#   db:
#     driver: local


